language: node_js
node_js:
- '0.10'
- '0.11'
- '0.12'
- '4.0'
- '4.1'
before_script:
- npm install
script:
- npm run build
deploy:
  skip_cleanup: true
  provider: npm
  email: npm@niteoholdings.com
  api_key:
    secure: WqD4+987Dg98HXzfanxbDoROjYXhFblrkCaqmz63OT3bWiAlK1P/TvqZfxXZnqwAohCU/Kak0a9kwPU7kYPEOBdYvOuhvo6gAnFGXa6IpKuU6K+oX5Z2RUUxtKtOBfflEZTK7OpBMVKUUdLqgfsQ6ppJqpCZp+97AX1WfVPUiT4=
  on:
    all_branches: true
    tags: true
    repo: VeriShip/grunt-niteo-cdbuild
    node: '4.1'
