language: node_js
node_js:
  - '0.10'
before_script:
  - npm install -g grunt-cli
  - npm install
script:
  - grunt
deploy:
  provider: npm
  email: npm@niteoholdings.com
  skip_cleanup: true
  api_key:
    secure: "MYbbsMRsYTcNqbokXK0Vdl3vRS+4LbePOMmh6B5Q1YlAEzqYeeGxcKyYqu42ujfbpSow16Ez0gY4lmDF+55DfEYgYLMXWztlgRQWTdVHNXO76oUwWrICapwKhIgoSqhAqpLjsKkXv7gMIpGorMzAJ+d/lBilbFQhFqokawsIItg="
  on:
    tags: true
    all_branches: true
    repo: NiteoSoftware/grunt-niteo-cdbuild

